### ISSUE TITLE
Feature request : project name CLI

### ISSUE THREAD

**Issue by Erim32** [sivaprasadreddy/generator-springboot#15]
That will be nice to be able to specified application name as option in CLI usage :

> yo springboot myservice

**Comment by sivaprasadreddy** [comment]
Currently the project name is the first option the generator will ask. While the generator can be updated to take first option as project name and skip asking for the same in prompts, I would prefer to keep things simple without implementing too many ways to achieve the same thing.

Please let me know what do you think of it?

**Comment by sivaprasadreddy** [comment]
Closing due to inactive.
