### ISSUE TITLE
remove dependency on JCenter for dependencies as it is sunsetting

### ISSUE THREAD

**Issue by rajadilipkolli** [sivaprasadreddy/generator-springboot#20]
jcenter is about to sunset in may 2021, I know that there is a huge dependency for gradle plugins on jcenter. We should slowly migrate to mavencentral

**Comment by sivaprasadreddy** [comment]
Jcenter repository is added for using https://github.com/avast/gradle-docker-compose-plugin in Gradle based projects.
If this plugin is already in Maven Central we can remove it.

**Comment by rajadileepkolli** [comment]
This is present in[ maven central](https://repo1.maven.org/maven2/com/avast/gradle/gradle-docker-compose-plugin/), so we can remove it

**Comment by sivaprasadreddy** [comment]
This Gradle plugin is used to automatically start dependent docker containers while running the app locally. However, there is no Maven equivalent of that. There is fabric8 maven plugin but that only works with docker-compose version v2 only and is no longer being maintained.

To have consistent feature parity between maven and gradle support I have removed gradle-docker-compose-plugin and fabric8-docker-plugin. For running the app locally users can simply run docker-compose command specified in README and run the app.
