### ISSUE TITLE
Creating Controller with Custom name is not importing packages correctly

### ISSUE THREAD

**Issue by rajadilipkolli** [sivaprasadreddy/generator-springboot#21]
I have tried to create Controller with name Order, it has created class files correctly but the import statements in controller and service class are wrong and pointing to customer package.

Expectation : import statements of entities, Service and Respository in controller should be pointing to correct path.

**Comment by sivaprasadreddy** [comment]
PR https://github.com/sivaprasadreddy/generator-springboot/pull/22 fixed this issue.
Thank you @rajadilipkolli :-)
