### ISSUE TITLE
Local changes to Yeoman Generator

### ISSUE THREAD

**Issue by cah-parita-desai** [sivaprasadreddy/generator-springboot#25]
I have used your generator as a base and have made some customization to address to organizational needs. I tested it locally using npm link and it worked as expected.
Committed the changes in my github repo. Now post taking the pull from git and running it i don't see my changes reflecting.
Please help!!

**Comment by sivaprasad-ee** [comment]
Looks like your repository is private, I can't view your changes.

**Comment by cah-parita-desai** [comment]
Yeah...You will not be able to view the changes.
When i see the logs it prints
7926 verbose stack Error: EEXIST: file already exists, cmd shim 'D:\Users\parita.desai\Documents\GitHub\generator\node_modules\atob\bin\atob.js' -> 'D:\Users\parita.desai\Documents\GitHub\generator\atob'

This i get when i do npm link

**Comment by cah-parita-desai** [comment]
Hi Siva,

Might be a silly question.

But as i have not published my changes to global npm module ie generator-springboot, i have to do npm link again to view my changes, right?

Note:- I can see all the code changes i have made and had tested it before commiting.

Any pointers would be of great help.

Thanks!!
________________________________

**Comment by sivaprasad-ee** [comment]
Yes, you can use npm link to work with local installation of yeoman generator.
If you want to publish to npm registry you can publish with different name.

**Comment by sivaprasadreddy** [comment]
Hi,
You can use "npm link" to use your changes done locally, but to publish to npm registry you will need to publish with different name.

**Comment by sivaprasadreddy** [comment]
Clarification provided, closing the issue.
