### ISSUE TITLE
Run google-java-format after project generation

### ISSUE THREAD

**Issue by sivaprasadreddy** [sivaprasadreddy/generator-springboot#26]
Formatting the templates as per google java format manually is a painful process especially when rendering something conditionally. So, a better approach could be running google java format goal after project code generation depending on selected build tool.

**Comment by sivaprasadreddy** [comment]
**More info to get started:**

To get an overview on how yeoman generator works see https://www.sivalabs.in/2020/01/creating-yeoman-based-springboot-generator/

We have already configured https://github.com/diffplug/spotless/tree/main/plugin-maven#google-java-format plugin for Maven and https://github.com/sherter/google-java-format-gradle-plugin for Gradle. 

We need to run `./mvnw spotless:apply` or `./gradlew googleJavaFormat ` commands during `install` or `end` lifecycle callbacks in `server` and `controller` generators.

We can use Shelljs (https://www.npmjs.com/package/shelljs) to run these commands.

**Comment by matheusemm** [comment]
I'll work on it. :-)
