### ISSUE TITLE
Improper db table names when using CamelCase variable name

### ISSUE THREAD

**Issue by GeoZac** [sivaprasadreddy/generator-springboot#47]
When creating entities with CamelCase scheme, the `@Table` entity is created with an improper naming scheme.
For eg. when issuing 
`yo springboot:controller ShoppingCart --base-path /api/shoppingcart` , then entity class has `@Table(name = "shopping carts")` which causes an *InvalidDataAccessResourceUsageException* when running the tests

**Comment by rajadilipkolli** [comment]
Hi @GeoZac , can you please test latest version and let us know incase if it is not working
