### ISSUE TITLE
Confusion with pageNumber on Pagination

### ISSUE THREAD

**Issue by GeoZac** [sivaprasadreddy/generator-springboot#56]
**Affected Branch** : 0.1.1

Glad that we now have pagination for entities, but I think the setting the page number on response will lead to confusion as the page number get increment on response. 
https://github.com/sivaprasadreddy/generator-springboot/blob/ba6a56ec293ef0fedbf90f2de124449398b2d9cd/generators/controller/templates/app/src/main/java/model/response/PagedResult.java#L26

This may lead to confusion as the we make the request for the first page, with index 0 and is returned the pageNumber 1. this is quite evident in the controller test where we make requires for 0th page and get returned the page with pageNumber 1,

https://github.com/sivaprasadreddy/generator-springboot/blob/ba6a56ec293ef0fedbf90f2de124449398b2d9cd/generators/controller/templates/app/src/test/java/web/controllers/ControllerTest.java#L60-L68

Can we have a look into this?

**Comment by rajadilipkolli** [comment]
Isn't it the first page we are requesting??

**Comment by GeoZac** [comment]
According to Spring, 1st page has pageNumber of 0

**Comment by rajadilipkolli** [comment]
@GeoZac isn't it the index number of the page but while displaying in UI, our Index will start from 1, hence incrementing to avoid confusion

cc: @sivaprasadreddy

**Comment by rajadilipkolli** [comment]
Closing as stated reasoning above
