### ISSUE TITLE
Support for other Liquibase migration formats (yaml, sql)

### ISSUE THREAD

**Issue by alexanderankin** [sivaprasadreddy/generator-springboot#60]
It might be of value to liquibase users to be able to write their migration in whatever format they are used to

**Comment by alexanderankin** [comment]
such as https://github.com/alexanderankin/generator-springboot/pull/1

**Comment by alexanderankin** [comment]
such as https://github.com/alexanderankin/generator-springboot/pull/1

**Comment by alexanderankin** [comment]
just read readme and saw the motivation was the preference for flyway 💀

**Comment by rajadilipkolli** [comment]
Can you please raise PR, it gives more options for liquibase

**Comment by sivaprasadreddy** [comment]
Flyway was my personal preference but we already have support for both Flyway and Liquibase.
But as of now Liquibase support is only in one format (xml). If you are interested to add support for more formats then you are welcome.

**Comment by rajadilipkolli** [comment]
This should be available one #70  is merged
