### ISSUE TITLE
Add support for restclients

### ISSUE THREAD

**Issue by rajadilipkolli** [sivaprasadreddy/generator-springboot#64]
Support for calling API using rest clients

Options are resttemplate , webclient and declarative clients

**Comment by sivaprasadreddy** [comment]
I am not sure there is any generic boilerplate code that we can generate for HttpClients. The actual interface and method definitions are application/client specific. 

@rajadilipkolli  Can you elaborate on what is the expected outcome for this feature?

**Comment by rajadilipkolli** [comment]
As we can't automate code for generating HttpClients as it is client specific, closing.
